apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: openweb-ui
  name: openweb-ui
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-01ec28e0eb27a06dc
  mountOptions:
  - tls
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem